-- =====================================================================
--  Points restants de l'audit du 13/09/2026 — à importer dans phpMyAdmin
--  (base du site, onglet Importer), UNE SEULE FOIS, AVANT de déployer le code.
--
--  1. Cadre = lieu, catégorie = thème : « lagune », « ocean » et « piscine »
--     ne sont plus des catégories (le cadre et l'équipement Piscine les
--     remplacent sur le site) ; « piscine » n'est plus un cadre.
--  2. Tarif des activités : mentions libres avant / après le prix, le texte
--     affiché étant désormais généré depuis le montant du devis.
--  3. Traductions EN / ES des fiches (villas, terrains, activités).
--
--  Le doublon Facebook et l'affichage du forfait week-end / des couchages
--  ne demandent aucune modification de la base.
-- =====================================================================

SET NAMES utf8mb4;

-- ---- Colonnes ---------------------------------------------------------
ALTER TABLE `villas`
  MODIFY COLUMN `category` VARCHAR(80) NOT NULL DEFAULT '' COMMENT 'thème (ref_categories.id), facultatif',
  ADD COLUMN `translations` JSON NULL COMMENT 'textes EN/ES de la fiche' AFTER `highlights`;

ALTER TABLE `terrains`
  ADD COLUMN `translations` JSON NULL COMMENT 'textes EN/ES de la fiche' AFTER `longitude`;

ALTER TABLE `activities`
  ADD COLUMN `price_prefix` VARCHAR(80) NOT NULL DEFAULT '' AFTER `group_size`,
  ADD COLUMN `price_suffix` VARCHAR(80) NOT NULL DEFAULT '' AFTER `price_prefix`,
  ADD COLUMN `translations` JSON NULL COMMENT 'textes EN/ES de la fiche' AFTER `price_suffix`;

-- ---- 1. Cadre = lieu, catégorie = thème -------------------------------
-- Villa au cadre « piscine » (Villa Akwaba) : terre ferme, sa case Piscine
-- est déjà cochée.
UPDATE `villas` SET `environment` = 'terre' WHERE `environment` = 'piscine';
UPDATE `villas` SET `category` = '', `category_label` = '' WHERE `category` IN ('lagune', 'ocean', 'piscine');
UPDATE `facebook_posts` SET `environment` = '' WHERE `environment` = 'piscine';
UPDATE `facebook_posts` SET `category` = '', `category_label` = '' WHERE `category` IN ('lagune', 'ocean', 'piscine');
DELETE FROM `ref_categories` WHERE `id` IN ('lagune', 'ocean', 'piscine');

-- ---- 2. Mentions du tarif des activités -----------------------------
UPDATE `activities` SET `price_prefix` = 'À partir de', `price_suffix` = '/ sortie', `price` = 'À partir de 60 000 FCFA / sortie' WHERE `id` = 'balade-bateau';
UPDATE `activities` SET `price_prefix` = '', `price_suffix` = '/ 30 min', `price` = '45 000 FCFA / 30 min' WHERE `id` = 'jet-ski';
UPDATE `activities` SET `price_prefix` = '', `price_suffix` = 'pour le groupe', `price` = '75 000 FCFA pour le groupe' WHERE `id` = 'iles-ehotiles';
UPDATE `activities` SET `price_prefix` = '', `price_suffix` = '/ quad', `price` = '35 000 FCFA / quad' WHERE `id` = 'randonnee-quad';
UPDATE `activities` SET `price_prefix` = 'Entrée', `price_suffix` = '', `price` = 'Entrée 5 000 FCFA / personne' WHERE `id` = 'parc-dipi';
UPDATE `activities` SET `price_prefix` = 'À partir de', `price_suffix` = '', `price` = 'À partir de 25 000 FCFA / jour' WHERE `id` = 'chef-prive';
UPDATE `activities` SET `price_prefix` = '', `price_suffix` = '', `price` = '10 000 FCFA / personne · 35 000 FCFA les 4' WHERE `id` = 'balade-lagunaire';
UPDATE `activities` SET `price_prefix` = '', `price_suffix` = '', `price` = '2 000 FCFA / personne' WHERE `id` = 'traversee-lagunaire';

-- ---- 3. Traductions (seulement si la fiche n'en a pas encore) ---------
UPDATE `villas` SET `translations` = '{"en":{"tagline":"Prestige villa with a private pontoon on the lagoon & mirror pool","description":"Nestled at the heart of the splendid Assinie-Mafia lagoon, Villa L''Oasis is a haven of calm and luxury. With a magnificent infinity pool opening straight onto the water and its own private pontoon, it is the perfect place to moor your boat or head straight out to La Passe. Its large, bright living room and modern open-plan kitchen open onto a spacious deck, ideal for sharing grilled dishes at sunset.","beds":"4 king-size beds + 2 living-room sofa beds","features":["Private infinity pool","Private mooring pontoon (lagoon)","Air conditioning throughout","High-speed fibre Wi-Fi","65'''' Smart TV (Canal+ & Netflix)","Fully equipped open-plan kitchen","Charcoal barbecue","Automatic backup generator","24-hour security guard","Daily cleaning & housekeeper","Lounge terrace & sun loungers","Secure private parking (4 cars)"],"highlights":["Direct boat access","Lagoon-side pool","Sunset views","Complete privacy"]},"es":{"tagline":"Villa de prestigio con embarcadero privado en la laguna y piscina espejo","description":"Enclavada en el corazón de la espléndida laguna de Assinie-Mafia, la Villa L''Oasis es un remanso de calma y lujo. Con una magnífica piscina infinita que da directamente al agua y su propio embarcadero privado, ofrece el marco perfecto para amarrar su barco o salir directamente hacia La Passe. Su amplio y luminoso salón y su moderna cocina americana se abren a una espaciosa terraza de madera donde da gusto compartir una parrillada al atardecer.","beds":"4 camas king size + 2 sofás cama en el salón","features":["Piscina infinita privada","Embarcadero privado de amarre (laguna)","Aire acondicionado en toda la villa","Wi-Fi de fibra de alta velocidad","Smart TV de 65'''' (Canal+ y Netflix)","Cocina americana totalmente equipada","Barbacoa de carbón","Generador automático","Guardia de seguridad 24 h","Limpieza diaria y ama de llaves","Terraza lounge y tumbonas","Aparcamiento privado vigilado (4 coches)"],"highlights":["Acceso directo en barco","Piscina frente a la laguna","Vistas al atardecer","Máxima intimidad"]}}' WHERE `id` = 'villa-oasis' AND `translations` IS NULL;
UPDATE `villas` SET `translations` = '{"en":{"tagline":"Beachfront seaside elegance on the Atlantic Ocean","description":"Treat yourself to the rare privilege of waking up to the gentle rush of Atlantic waves. Set on the Assinie coastline, Résidence Palm Beach combines contemporary architecture with fine hardwood finishes. Its turquoise pool overlooks a wild beach sheltered by a row of majestic coconut palms. Ideal for large families and trips with friends in search of a true escape.","beds":"5 air-conditioned queen-size beds","features":["Direct access to the fine sandy beach","Private pool with teak deck","5 air-conditioned sea-view suites","Outdoor Bluetooth sound system","High-speed Starlink Wi-Fi","Chef''s kitchen with central island","Giant barbecue under a straw hut","Backup generator","24/7 security & alarm","Dedicated chef available on request","Tropical sun loungers & parasols","Outdoor beach shower"],"highlights":["Right on the ocean","Giant barbecue","Very fast Starlink","Exclusive setting"]},"es":{"tagline":"Elegancia costera a pie de playa frente al océano Atlántico","description":"Regálese el raro privilegio de despertar con el suave rumor de las olas del océano Atlántico. Situada en la franja costera de Assinie, la Résidence Palm Beach combina arquitectura contemporánea y acabados en maderas nobles. Su piscina turquesa domina una playa salvaje protegida por una hilera de majestuosos cocoteros. Ideal para familias numerosas y estancias entre amigos en busca de una auténtica evasión.","beds":"5 camas queen size climatizadas","features":["Acceso directo a la playa de arena fina","Piscina privada con terraza de teca","5 suites climatizadas con vistas al mar","Sistema de sonido exterior Bluetooth","Wi-Fi Starlink de alta velocidad","Cocina de chef con isla central","Barbacoa gigante bajo una cabaña de paja","Generador de emergencia","Vigilancia 24/7 y alarma","Posibilidad de cocinero exclusivo","Tumbonas y sombrillas tropicales","Ducha exterior de playa"],"highlights":["A pie de océano","Barbacoa gigante","Starlink muy rápido","Entorno exclusivo"]}}' WHERE `id` = 'residence-palm-beach' AND `translations` IS NULL;
UPDATE `villas` SET `translations` = '{"en":{"tagline":"Tropical haven of peace with a leafy garden and private pool","description":"A warm and friendly atmosphere awaits you at Villa Akwaba. Surrounded by lush bougainvillea and palm trees, this single-storey villa offers a secure private pool, ideal for children. The large covered terrace is the perfect spot to enjoy braised fish or fresh lobster in the finest Ivorian tradition.","beds":"3 king-size beds + 1 extra bed","features":["Private pool in the middle of the garden","3 air-conditioned self-contained bedrooms","Shaded terrace with seating for 10","High-speed Wi-Fi","Flat-screen TV with Canal+","Fully equipped kitchen (cooker, oven, microwave, fridge)","Weber barbecue area","Caretaker and security guard","Board games and relaxation area","Fenced parking"],"highlights":["Ideal for children & families","Tropical garden","Excellent value for money"]},"es":{"tagline":"Remanso de paz tropical con jardín arbolado y piscina privada","description":"Un ambiente cálido y acogedor le espera en la Villa Akwaba. Rodeada de una exuberante vegetación de buganvillas y palmeras, esta villa de una sola planta ofrece una piscina privada segura, ideal para los niños. La gran terraza cubierta le permitirá saborear un buen pescado a la brasa o una langosta fresca según la más pura tradición marfileña.","beds":"3 camas king size + 1 cama supletoria","features":["Piscina privada en el centro del jardín","3 dormitorios independientes climatizados","Terraza a la sombra con mesa para 10","Wi-Fi de alta velocidad","TV de pantalla plana con Canal+","Cocina totalmente equipada (cocina de gas, horno, microondas, nevera)","Zona de barbacoa Weber","Personal de mantenimiento y guarda","Juegos de mesa y zona de descanso","Aparcamiento vallado"],"highlights":["Ideal para niños y familias","Jardín tropical","Excelente relación calidad-precio"]}}' WHERE `id` = 'villa-akwaba' AND `translations` IS NULL;
UPDATE `villas` SET `translations` = '{"en":{"tagline":"A grand estate for receptions, weddings, seminars & large groups","description":"Le Domaine Éden is a prestige property without equal in Assinie, set in more than 2,500 m² of landscaped grounds. Designed for lavish entertaining, it features a monumental pool with a swim-up bar, a covered reception pavilion for 80 guests, a professional catering kitchen and 7 upmarket suites. It is the address of choice for corporate retreats, intimate weddings and milestone birthdays.","beds":"7 large suites with private bathrooms","features":["XXL pool with swim-up bar","Landscaped grounds for receptions (up to 80 guests)","7 independent air-conditioned suites","Seminar space with projector & sound system","Professional catering kitchen","Large private pontoon on the lagoon","Chef and maître d'' available","Enhanced 24/7 security with CCTV","Soundproofed industrial generator","Powerful Wi-Fi across the whole estate","Large car park for over 10 vehicles"],"highlights":["Sleeps 18","Up to 80 guests for cocktails","Swim-up bar","VIP catering services"]},"es":{"tagline":"Una gran finca para recepciones, bodas, seminarios y grupos grandes","description":"Le Domaine Éden es una propiedad de prestigio sin igual en Assinie, que se extiende sobre más de 2.500 m² de jardines paisajísticos. Concebido para recibir a lo grande, cuenta con una piscina monumental con bar acuático, un pabellón de recepción cubierto para 80 invitados, una cocina profesional de catering y 7 suites de alta gama. Es la dirección de referencia para retiros de empresa, bodas íntimas y grandes aniversarios.","beds":"7 grandes suites con baño privado","features":["Piscina XXL con bar acuático","Parque paisajístico para recepciones (hasta 80 personas)","7 suites independientes climatizadas","Espacio para seminarios con proyector y sonido","Cocina profesional de catering","Gran embarcadero privado en la laguna","Chef y maître disponibles","Seguridad reforzada 24/7 con videovigilancia","Generador industrial insonorizado","Wi-Fi potente en toda la finca","Gran aparcamiento para más de 10 vehículos"],"highlights":["18 plazas para dormir","Hasta 80 invitados en cóctel","Bar acuático","Servicio de catering VIP"]}}' WHERE `id` = 'domaine-eden' AND `translations` IS NULL;
UPDATE `villas` SET `translations` = '{"en":{"tagline":"A cosy, intimate retreat for couples and romantic getaways","description":"Pavillon Sérénité is a charming architect-designed duplex, perfect for a romantic weekend for two or for two couples of friends. Enjoy a peaceful lounge atmosphere, cosy bedrooms with flower-filled balconies, a refreshing private plunge pool and a hammock beneath the coconut palms to recharge far from the bustle of Abidjan.","beds":"2 air-conditioned queen-size beds","features":["Refreshing private plunge pool / outdoor jacuzzi","2 cosy air-conditioned bedrooms upstairs","Balcony with sunset views","Equipped kitchen & Nespresso machine","Intimate lounge with Smart TV","Fast Wi-Fi","Hammock and quiet reading corner","Breakfast service on request","Discreet 24/7 security"],"highlights":["Intimate atmosphere","Perfect for couples","Complete tranquillity"]},"es":{"tagline":"Un nido acogedor e íntimo para parejas y escapadas románticas","description":"El Pavillon Sérénité es un encantador dúplex de arquitecto, perfecto para un fin de semana romántico a solas o para dos parejas de amigos. Disfrute de un ambiente lounge tranquilo, dormitorios acogedores con balcones floridos, una refrescante piscina privada y una hamaca bajo los cocoteros para desconectar lejos del bullicio de Abiyán.","beds":"2 camas queen size climatizadas","features":["Piscina privada refrescante / jacuzzi exterior","2 dormitorios acogedores climatizados en la planta alta","Balcón con vistas al atardecer","Cocina equipada y cafetera Nespresso","Salón íntimo con Smart TV","Wi-Fi rápido","Hamaca y rincón de lectura","Servicio de desayuno bajo petición","Vigilancia discreta 24/7"],"highlights":["Ambiente íntimo","Perfecto para parejas","Calma absoluta"]}}' WHERE `id` = 'pavillon-serenite' AND `translations` IS NULL;
UPDATE `villas` SET `translations` = '{"en":{"tagline":"Contemporary architecture with spectacular sunsets over the lagoon","description":"Facing due west for magical sunsets! Villa Sunset Paradise blends ultra-modern, clean-lined design with the authenticity of the Assinie lagoon. Wide sliding glass doors create a seamless flow between the air-conditioned living room and the vast outdoor terrace with its infinity pool and floating lounge on the pontoon.","beds":"4 large suites with lagoon views","features":["Mirror pool facing the setting sun","Large furnished pontoon with lounge area","4 air-conditioned suites with dressing rooms and lagoon views","Billiard table & games","High-speed Starlink Wi-Fi","High-end open-plan kitchen","Barbecue & plancha area","Automatic backup power system","Housekeeper and night watchman","Easy access to pirogues and boats to La Passe"],"highlights":["Magical sunsets","Billiard table","Lounge pontoon","Luxury finish"]},"es":{"tagline":"Arquitectura contemporánea con espectaculares puestas de sol sobre la laguna","description":"¡Orientación plena al oeste para unas puestas de sol mágicas! La Villa Sunset Paradise combina un diseño depurado y ultramoderno con la autenticidad de la laguna de Assinie. Los amplios ventanales correderos crean una continuidad perfecta entre el salón climatizado y la inmensa terraza exterior con piscina infinita y salón flotante en el embarcadero.","beds":"4 grandes suites con vistas a la laguna","features":["Piscina espejo frente a la puesta de sol","Gran embarcadero acondicionado con salón lounge","4 suites climatizadas con vestidor y vistas a la laguna","Mesa de billar y juegos","Wi-Fi Starlink de alta velocidad","Cocina americana de alta gama","Zona de barbacoa y plancha","Sistema eléctrico de emergencia automático","Ama de llaves y vigilante nocturno","Fácil acceso a piraguas y barcos hacia La Passe"],"highlights":["Puestas de sol mágicas","Mesa de billar","Embarcadero lounge","Acabados de gran lujo"]}}' WHERE `id` = 'villa-sunset-paradise' AND `translations` IS NULL;
UPDATE `terrains` SET `translations` = '{"en":{"title":"Waterfront plot — Aby Lagoon","description":"Rectangular 1,200 m² plot with 24 metres of direct frontage on the Aby Lagoon. Flat, backfilled and surveyed land, suitable for building a villa with a private pontoon. Water and electricity connections at the plot boundary. Access by tarmac road from the Assinie road.","highlights":["24 m of lagoon frontage","Surveyed and backfilled land","Private pontoon possible","Tarmac road up to the plot"]},"es":{"title":"Parcela a orillas del agua — Laguna Aby","description":"Parcela rectangular de 1.200 m² con 24 metros de fachada directa a la laguna Aby. Terreno llano, rellenado y amojonado, apto para construir una villa con embarcadero privado. Acometidas de agua y electricidad en el límite de la parcela. Acceso por carretera asfaltada desde la carretera de Assinie.","highlights":["24 m de fachada a la laguna","Terreno amojonado y rellenado","Embarcadero privado posible","Carretera asfaltada hasta la parcela"]}}' WHERE `id` = 'terrain-lagune-km12' AND `translations` IS NULL;
UPDATE `terrains` SET `translations` = '{"en":{"title":"Seaside plot, second row — Ocean","description":"800 m² plot set in the second row back from the beach, 120 metres from the ocean. Already fenced on three sides. Quiet residential area, ideal for a holiday home or a seasonal rental project.","highlights":["120 m from the ocean","Already fenced","ACD transfer in progress","Quiet residential area"]},"es":{"title":"Terreno costero en segunda línea — Océano","description":"Parcela de 800 m² situada en segunda línea de playa, a 120 metros del océano. Ya vallada por tres lados. Entorno residencial tranquilo, ideal para una segunda residencia o un proyecto de alquiler de temporada.","highlights":["A 120 m del océano","Ya vallado","ACD en proceso de transmisión","Zona residencial tranquila"]}}' WHERE `id` = 'terrain-ocean-mafia' AND `translations` IS NULL;
UPDATE `terrains` SET `translations` = '{"en":{"title":"Serviced lot — Résidence de La Passe","description":"500 m² lot in a fully serviced development: roads, water network, electricity and sewerage in place. Boundaries surveyed, subdivision plan approved. Close to shops and the landing stage.","highlights":["Serviced development","Boundaries surveyed","Close to the landing stage","Sewerage in place"]},"es":{"title":"Lote urbanizado — Résidence de La Passe","description":"Lote de 500 m² en una urbanización con todos los servicios: viales, red de agua, electricidad y saneamiento instalados. Amojonamiento realizado y plan de parcelación aprobado. Cerca de los comercios y del embarcadero.","highlights":["Urbanización con servicios","Amojonamiento realizado","Cerca del embarcadero","Saneamiento instalado"]}}' WHERE `id` = 'terrain-lotissement-passe' AND `translations` IS NULL;
UPDATE `terrains` SET `translations` = '{"en":{"title":"Large leisure plot — 3,000 m²","description":"Large 3,000 m² plot planted with coconut palms, suited to a hotel project, an eco-lodge or a large family residence. Land title available, land free of any occupation.","highlights":["3,000 m² in a single plot","Planted with coconut palms","Land title available","Free of any occupation"]},"es":{"title":"Gran parcela de recreo — 3.000 m²","description":"Gran parcela de 3.000 m² plantada de cocoteros, adecuada para un proyecto hotelero, un ecolodge o una residencia familiar de gran capacidad. Título de propiedad disponible, terreno libre de toda ocupación.","highlights":["3.000 m² de una sola pieza","Plantado de cocoteros","Título de propiedad disponible","Libre de toda ocupación"]}}' WHERE `id` = 'terrain-grand-lot-agrement' AND `translations` IS NULL;
UPDATE `activities` SET `translations` = '{"en":{"title":"Private Boat Trip to La Passe","subtitle":"The Assinie must-do","duration":"2 hours or half a day","pricePrefix":"From","priceSuffix":"/ trip","description":"Set off from your villa''s pontoon for a cruise along the lagoon to the legendary Passe d''Assinie, where the calm waters of the Aby Lagoon meet the Atlantic swell. Stop on the unspoilt sandbanks."},"es":{"title":"Paseo privado en barco hasta La Passe","subtitle":"Imprescindible en Assinie","duration":"2 horas o media jornada","pricePrefix":"Desde","priceSuffix":"/ salida","description":"Embarque desde el embarcadero de su villa para navegar por la laguna hasta la mítica Passe d''Assinie, donde las aguas tranquilas de la laguna Aby se encuentran con el oleaje del océano Atlántico. Parada en los bancos de arena vírgenes."}}' WHERE `id` = 'balade-bateau' AND `translations` IS NULL;
UPDATE `activities` SET `translations` = '{"en":{"title":"Jet Ski & Towed Ring Thrills","subtitle":"Adrenaline on the lagoon","duration":"30 min or 1 hour","description":"Ride latest-generation jet skis safely across the wide, calm waters of the Assinie lagoon. Towed rings available for plenty of laughs with family or friends."},"es":{"title":"Emociones en moto acuática y rosco remolcado","subtitle":"Adrenalina en la laguna","duration":"30 min o 1 hora","description":"Pilote motos acuáticas de última generación con total seguridad por las amplias aguas tranquilas de la laguna de Assinie. Posibilidad de rosco remolcado para reír a carcajadas en familia o con amigos."}}' WHERE `id` = 'jet-ski' AND `translations` IS NULL;
UPDATE `activities` SET `translations` = '{"en":{"title":"Excursion to the Ehotilé Islands","subtitle":"National Park & Wild Nature","duration":"Half day with guide","priceSuffix":"for the group","description":"Guided discovery of the historic Ehotilé Islands archipelago, a protected nature reserve home to exceptional wildlife, manatees, migratory birds and sacred century-old trees."},"es":{"title":"Excursión a las islas Ehotilé","subtitle":"Parque nacional y naturaleza salvaje","duration":"Media jornada con guía","priceSuffix":"para el grupo","description":"Descubrimiento guiado del histórico archipiélago de las islas Ehotilé, reserva natural protegida que alberga una fauna excepcional, manatíes, aves migratorias y árboles centenarios sagrados."}}' WHERE `id` = 'iles-ehotiles' AND `translations` IS NULL;
UPDATE `activities` SET `translations` = '{"en":{"title":"Quad Bike Ride on Trails & Beaches","subtitle":"Off-road adventure","duration":"1 h 30 circuit","description":"Set off on a guided ride along sandy trails lined with coconut palms and the deserted beaches of Assinie-Mafia. An exhilarating way to see the region from a different angle."},"es":{"title":"Ruta en quad por pistas y playas","subtitle":"Aventura todoterreno","duration":"Circuito de 1 h 30","description":"Parta en una ruta guiada por pistas arenosas bordeadas de cocoteros y playas desiertas de Assinie-Mafia. Una experiencia apasionante para descubrir la región desde otro ángulo."}}' WHERE `id` = 'randonnee-quad' AND `translations` IS NULL;
UPDATE `activities` SET `translations` = '{"en":{"title":"Visit to Dipi Zoological Park","subtitle":"Meet the local wildlife","duration":"1 h 30 visit","pricePrefix":"Entry","description":"Ideal for children and nature lovers: visit the Dipi sanctuary in Assinie, famous for its giant crocodiles, monkeys, snakes and giant tortoises in a green, shady setting."},"es":{"title":"Visita al parque zoológico Dipi","subtitle":"Encuentro con la fauna local","duration":"Visita de 1 h 30","pricePrefix":"Entrada","description":"Ideal para niños y amantes de la naturaleza: visite el santuario Dipi en Assinie, famoso por sus cocodrilos gigantes, monos, serpientes y tortugas gigantes en un entorno verde y sombreado."}}' WHERE `id` = 'parc-dipi' AND `translations` IS NULL;
UPDATE `activities` SET `translations` = '{"en":{"title":"Private Chef & Lagoon Dining","subtitle":"Gastronomy & local flavours","duration":"Per day or weekend","pricePrefix":"From","description":"Enjoy at your villa carp and grouper braised over a wood fire, fresh Assinie lobster grilled with parsley butter, attiéké with red palm oil, golden alloco or European menus prepared by our dedicated chef."},"es":{"title":"Chef privado y gastronomía de la laguna","subtitle":"Gastronomía y sabores locales","duration":"Por día o fin de semana","pricePrefix":"Desde","description":"Deguste en la villa carpas y meros a la brasa de leña, langostas frescas de Assinie a la parrilla con mantequilla de perejil, attiéké con aceite rojo, alloco dorado o menús europeos preparados por nuestro chef exclusivo."}}' WHERE `id` = 'chef-prive' AND `translations` IS NULL;
UPDATE `activities` SET `translations` = '{"en":{"title":"Guided lagoon trip by pirogue or canoe","subtitle":"Mangroves, lakeside villages and birds of the Aby Lagoon","duration":"2 hours to half a day","description":"Glide across the water aboard a traditional pirogue paddled by boatmen from the village. The route follows the wooded shores of the Aby Lagoon, slips beneath tunnels of mangrove trees and lingers where herons, egrets and kingfishers can be approached. Your guide tells the story of lagoon life: net fishing, the lakeside villages, the mangrove species and their uses. Departures at sunrise or late afternoon, when the light is softest and the water calmest. Life jackets provided; the trip is open to everyone, including accompanied children. Canoes available on request for those who prefer to paddle themselves."},"es":{"title":"Paseo guiado por la laguna en piragua o canoa","subtitle":"Manglares, pueblos lacustres y aves de la laguna Aby","duration":"De 2 h a media jornada","description":"Deslícese sobre el agua a bordo de una piragua tradicional impulsada a remo por piragüeros del pueblo. El recorrido bordea las orillas arboladas de la laguna Aby, se adentra en los túneles de manglares y se detiene allí donde garzas, garcetas y martines pescadores se dejan observar de cerca. Su guía le cuenta la vida de la laguna: la pesca con red, los pueblos lacustres, las especies del manglar y sus usos. Salida al amanecer o al final de la tarde, cuando la luz es más suave y el agua está más tranquila. Chalecos salvavidas incluidos; salida apta para todos, también para niños acompañados. Canoa disponible bajo petición para quienes prefieran remar ellos mismos."}}' WHERE `id` = 'balade-lagunaire' AND `translations` IS NULL;
UPDATE `activities` SET `translations` = '{"en":{"title":"Lagoon crossing to your residence","subtitle":"Our private boat from the Assinie pontoon","duration":"About 20 min crossing","description":"Assinie is reached by water: we meet you at the pontoon and take you straight to the foot of your residence aboard our own boat. The crossing takes about twenty minutes, under a roof that shelters you from the sun, between coconut palms and houses set along the lagoon shore — often the first real moment of your stay. Timed to match your arrival, including late in the day, with the return trip arranged on your departure day. Life jackets on board and space provided for bulky luggage. The price is per person."},"es":{"title":"Travesía por la laguna hasta su residencia","subtitle":"Nuestro barco privado desde el embarcadero de Assinie","duration":"Unos 20 min de travesía","description":"A Assinie se llega por agua: le esperamos en el embarcadero y le llevamos directamente hasta su residencia a bordo de nuestro propio barco. La travesía dura unos veinte minutos, bajo un techo que protege del sol, entre cocoteros y casas a orillas de la laguna: a menudo es el primer momento de verdad de la estancia. Horario ajustado a su llegada, también a última hora del día, y regreso organizado el día de la salida. Chalecos salvavidas a bordo y espacio previsto para el equipaje voluminoso. La tarifa es por persona."}}' WHERE `id` = 'traversee-lagunaire' AND `translations` IS NULL;
