-- =====================================================================
--  Détente & Loisirs à Assinie — données du site
--  Généré depuis data/site-content.json le 2026-09-10
--  Rejouable sans risque : ON DUPLICATE KEY UPDATE sur chaque ligne.
-- =====================================================================
SET NAMES utf8mb4;

-- 6 ligne(s) dans `villas`
INSERT INTO `villas` (`id`, `name`, `tagline`, `category`, `category_label`, `location`, `description`, `price_per_night`, `price_euro`, `weekend_package`, `capacity`, `bedrooms`, `bathrooms`, `beds`, `status`, `badge`, `visible`, `featured`, `rating`, `reviews_count`, `images`, `features`, `highlights`, `sort_order`)
  VALUES ("villa-oasis", "Villa L'Oasis d'Assinie", "Villa de prestige avec ponton privé sur la lagune & piscine miroir", "lagune", "Bord de Lagune", "Assinie-Mafia, Km 14 (Bord de lagune)", "Nichée au cœur de la splendide lagune d'Assinie-Mafia, la Villa L'Oasis est un écrin de calme et de luxe. Dotée d'une magnifique piscine à débordement donnant directement sur l'eau et de son propre ponton privatif, elle offre un cadre parfait pour amarrer votre bateau ou profiter de départs directs vers La Passe. Son grand salon lumineux et sa cuisine américaine moderne s'ouvrent sur un deck spacieux où il fait bon partager des grillades au coucher du soleil.", 250000, 381, 450000, 10, 4, 4, "4 lits King Size + 2 banquettes salon", "disponible", "Coup de Cœur", 1, 1, 4.95, 38, "[\"assets/images/residence-villa-luxe.jpg\",\"https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80\"]", "[\"Piscine privée à débordement\",\"Ponton privé d'amarrage (Lagune)\",\"Climatisation intégrale\",\"Wi-Fi Fibre Haut Débit\",\"Smart TV 65'' (Canal+ & Netflix)\",\"Cuisine américaine super équipée\",\"Barbecue au charbon de bois\",\"Groupe électrogène automatique\",\"Gardien de sécurité 24h/24\",\"Ménage quotidien & gouvernante\",\"Terrasse lounge & transats\",\"Parking privé sécurisé (4 voitures)\"]", "[\"Accès bateau direct\",\"Piscine lagon\",\"Vue coucher de soleil\",\"Haute intimité\"]", 0)
  ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `tagline`=VALUES(`tagline`), `category`=VALUES(`category`), `category_label`=VALUES(`category_label`), `location`=VALUES(`location`), `description`=VALUES(`description`), `price_per_night`=VALUES(`price_per_night`), `price_euro`=VALUES(`price_euro`), `weekend_package`=VALUES(`weekend_package`), `capacity`=VALUES(`capacity`), `bedrooms`=VALUES(`bedrooms`), `bathrooms`=VALUES(`bathrooms`), `beds`=VALUES(`beds`), `status`=VALUES(`status`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `rating`=VALUES(`rating`), `reviews_count`=VALUES(`reviews_count`), `images`=VALUES(`images`), `features`=VALUES(`features`), `highlights`=VALUES(`highlights`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `villas` (`id`, `name`, `tagline`, `category`, `category_label`, `location`, `description`, `price_per_night`, `price_euro`, `weekend_package`, `capacity`, `bedrooms`, `bathrooms`, `beds`, `status`, `badge`, `visible`, `featured`, `rating`, `reviews_count`, `images`, `features`, `highlights`, `sort_order`)
  VALUES ("residence-palm-beach", "Résidence Palm Beach Luxury", "Élégance balnéaire pieds dans l'eau côté océan Atlantique", "ocean", "Bord d'Océan", "Assinie Terminal (Accès direct plage)", "Offrez-vous le privilège rare de vous réveiller avec le doux ressac des vagues de l'océan Atlantique. Située sur la bande côtière d'Assinie, la Résidence Palm Beach allie architecture contemporaine et finitions en bois précieux. Sa piscine turquoise surplombe la plage sauvage protégée par une rangée de cocotiers majestueux. Idéale pour les grandes familles et les séjours entre amis à la recherche d'évasion pure.", 320000, 488, 580000, 12, 5, 5, "5 lits Queen Size climatisés", "disponible", "Plage Privée", 1, 1, 4.9, 29, "[\"assets/images/residence-ocean-assinie.jpg\",\"https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80\"]", "[\"Accès direct à la plage de sable fin\",\"Piscine privée avec deck en teck\",\"5 suites climatisées vue mer\",\"Système sono extérieur Bluetooth\",\"Wi-Fi Starlink haut débit\",\"Cuisine de chef & îlot central\",\"Barbecue géant sous paillote\",\"Groupe électrogène de secours\",\"Gardiennage 24/7 & alarme\",\"Possibilité de chef cuisinier dédié\",\"Transats & parasols tropicaux\",\"Douche extérieure de plage\"]", "[\"Pieds dans l'eau océan\",\"Barbecue géant\",\"Starlink très rapide\",\"Cadre exclusif\"]", 1)
  ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `tagline`=VALUES(`tagline`), `category`=VALUES(`category`), `category_label`=VALUES(`category_label`), `location`=VALUES(`location`), `description`=VALUES(`description`), `price_per_night`=VALUES(`price_per_night`), `price_euro`=VALUES(`price_euro`), `weekend_package`=VALUES(`weekend_package`), `capacity`=VALUES(`capacity`), `bedrooms`=VALUES(`bedrooms`), `bathrooms`=VALUES(`bathrooms`), `beds`=VALUES(`beds`), `status`=VALUES(`status`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `rating`=VALUES(`rating`), `reviews_count`=VALUES(`reviews_count`), `images`=VALUES(`images`), `features`=VALUES(`features`), `highlights`=VALUES(`highlights`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `villas` (`id`, `name`, `tagline`, `category`, `category_label`, `location`, `description`, `price_per_night`, `price_euro`, `weekend_package`, `capacity`, `bedrooms`, `bathrooms`, `beds`, `status`, `badge`, `visible`, `featured`, `rating`, `reviews_count`, `images`, `features`, `highlights`, `sort_order`)
  VALUES ("villa-akwaba", "Villa Akwaba Lagoon", "Havre de paix tropical avec jardin arboré et piscine privative", "piscine", "Piscine Privée", "Assinie-Mafia, Km 9", "Une atmosphère chaleureuse et conviviale vous attend à la Villa Akwaba. Entourée d'une végétation luxuriante de bougainvilliers et de palmiers, cette villa de plain-pied offre une piscine privée sécurisée, idéale pour les enfants. La grande terrasse couverte vous permettra de savourer un bon poisson braisé ou une langouste fraîche dans la plus pure tradition ivoirienne.", 180000, 274, 330000, 8, 3, 3, "3 lits King Size + 1 lit d'appoint", "disponible", "Famille & Amis", 1, 0, 4.88, 44, "[\"https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1200&q=80\"]", "[\"Piscine privée au centre du jardin\",\"3 chambres autonomes climatisées\",\"Terrasse ombragée avec table 10 couverts\",\"Wi-Fi haut débit\",\"TV écran plat avec Canal+\",\"Cuisine toute équipée (gazinière, four, micro-ondes, frigo)\",\"Espace barbecue Weber\",\"Agent d'entretien et gardien\",\"Jeux de société et espace détente\",\"Stationnement clôturé\"]", "[\"Idéal enfants & familles\",\"Jardin tropical\",\"Excellent rapport qualité/prix\"]", 2)
  ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `tagline`=VALUES(`tagline`), `category`=VALUES(`category`), `category_label`=VALUES(`category_label`), `location`=VALUES(`location`), `description`=VALUES(`description`), `price_per_night`=VALUES(`price_per_night`), `price_euro`=VALUES(`price_euro`), `weekend_package`=VALUES(`weekend_package`), `capacity`=VALUES(`capacity`), `bedrooms`=VALUES(`bedrooms`), `bathrooms`=VALUES(`bathrooms`), `beds`=VALUES(`beds`), `status`=VALUES(`status`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `rating`=VALUES(`rating`), `reviews_count`=VALUES(`reviews_count`), `images`=VALUES(`images`), `features`=VALUES(`features`), `highlights`=VALUES(`highlights`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `villas` (`id`, `name`, `tagline`, `category`, `category_label`, `location`, `description`, `price_per_night`, `price_euro`, `weekend_package`, `capacity`, `bedrooms`, `bathrooms`, `beds`, `status`, `badge`, `visible`, `featured`, `rating`, `reviews_count`, `images`, `features`, `highlights`, `sort_order`)
  VALUES ("domaine-eden", "Le Domaine Éden Assinie", "Domaine grandiose pour réceptions, mariages, séminaires & grands groupes", "evenement", "Événements & Séminaires", "Assinie-Mafia, Km 18", "Le Domaine Éden est une propriété de prestige sans équivalent à Assinie, s'étendant sur plus de 2 500 m² de terrain paysager. Conçu spécialement pour recevoir avec faste, il abrite une piscine monumentale avec bar aquatique immergé, un préau de réception couvert pour 80 convives, une cuisine de traiteur professionnelle et 7 suites haut de gamme. C'est l'adresse de référence pour les retraites d'entreprise, les mariages intimes et les grands anniversaires.", 500000, 762, 920000, 18, 7, 8, "7 grandes suites avec salles de bain privatives", "disponible", "Grands Groupes", 1, 1, 4.98, 19, "[\"https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80\"]", "[\"Piscine XXL avec bar aquatique\",\"Parc paysager pour réceptions (jusqu'à 80 pers.)\",\"7 suites indépendantes climatisées\",\"Espace séminaire avec projecteur & sono\",\"Cuisine professionnelle traiteur\",\"Grand ponton privé sur la lagune\",\"Chef et maître d'hôtel disponibles\",\"Sécurité renforcée 24/7 avec vidéosurveillance\",\"Groupe électrogène industriel insonorisé\",\"Wi-Fi ultra-puissant sur tout le domaine\",\"Grand parking pour plus de 10 véhicules\"]", "[\"Capacité 18 couchages\",\"Jusqu'à 80 invités cocktail\",\"Bar aquatique\",\"Prestations traiteur VIP\"]", 3)
  ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `tagline`=VALUES(`tagline`), `category`=VALUES(`category`), `category_label`=VALUES(`category_label`), `location`=VALUES(`location`), `description`=VALUES(`description`), `price_per_night`=VALUES(`price_per_night`), `price_euro`=VALUES(`price_euro`), `weekend_package`=VALUES(`weekend_package`), `capacity`=VALUES(`capacity`), `bedrooms`=VALUES(`bedrooms`), `bathrooms`=VALUES(`bathrooms`), `beds`=VALUES(`beds`), `status`=VALUES(`status`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `rating`=VALUES(`rating`), `reviews_count`=VALUES(`reviews_count`), `images`=VALUES(`images`), `features`=VALUES(`features`), `highlights`=VALUES(`highlights`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `villas` (`id`, `name`, `tagline`, `category`, `category_label`, `location`, `description`, `price_per_night`, `price_euro`, `weekend_package`, `capacity`, `bedrooms`, `bathrooms`, `beds`, `status`, `badge`, `visible`, `featured`, `rating`, `reviews_count`, `images`, `features`, `highlights`, `sort_order`)
  VALUES ("pavillon-serenite", "Pavillon Sérénité - Duplex Privé", "Nid douillet intime pour couples et escapades romantiques", "romantique", "Escapade Romantique", "Assinie, Km 6", "Le Pavillon Sérénité est un charmant duplex architectural parfait pour un week-end romantique en tête-à-tête ou pour deux couples d'amis. Profitez d'une atmosphère lounge paisible, de chambres douillettes avec balcons fleuris, d'un bassin d'eau rafraîchissant privatif et d'un hamac sous les cocotiers pour vous ressourcer loin de l'effervescence d'Abidjan.", 120000, 183, 220000, 4, 2, 2, "2 lits Queen Size climatisés", "disponible", "Spécial Couple", 1, 0, 4.92, 33, "[\"https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80\"]", "[\"Bassin privé rafraîchissant / Jacuzzi extérieur\",\"2 chambres cosy à l'étage climatisées\",\"Balcon avec vue sur le coucher de soleil\",\"Cuisine équipée & machine Nespresso\",\"Salon intime avec Smart TV\",\"Wi-Fi rapide\",\"Hamac et coin lecture détente\",\"Service petit-déjeuner sur demande\",\"Gardiennage discret 24/7\"]", "[\"Ambiance intimiste\",\"Parfait pour couples\",\"Calme absolu\"]", 4)
  ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `tagline`=VALUES(`tagline`), `category`=VALUES(`category`), `category_label`=VALUES(`category_label`), `location`=VALUES(`location`), `description`=VALUES(`description`), `price_per_night`=VALUES(`price_per_night`), `price_euro`=VALUES(`price_euro`), `weekend_package`=VALUES(`weekend_package`), `capacity`=VALUES(`capacity`), `bedrooms`=VALUES(`bedrooms`), `bathrooms`=VALUES(`bathrooms`), `beds`=VALUES(`beds`), `status`=VALUES(`status`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `rating`=VALUES(`rating`), `reviews_count`=VALUES(`reviews_count`), `images`=VALUES(`images`), `features`=VALUES(`features`), `highlights`=VALUES(`highlights`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `villas` (`id`, `name`, `tagline`, `category`, `category_label`, `location`, `description`, `price_per_night`, `price_euro`, `weekend_package`, `capacity`, `bedrooms`, `bathrooms`, `beds`, `status`, `badge`, `visible`, `featured`, `rating`, `reviews_count`, `images`, `features`, `highlights`, `sort_order`)
  VALUES ("villa-sunset-paradise", "Villa Sunset Paradise", "Architecture contemporaine avec coucher de soleil spectaculaire sur la lagune", "lagune", "Bord de Lagune", "Assinie-Mafia, Km 16", "Orientation plein ouest pour des couchers de soleil féeriques ! La Villa Sunset Paradise marie un design épuré ultra-moderne à l'authenticité de la lagune d'Assinie. Les larges baies vitrées coulissantes créent une continuité parfaite entre le séjour climatisé et l'immense terrasse extérieure avec piscine à débordement et salon flottant sur le ponton.", 280000, 427, 500000, 10, 4, 4, "4 grandes suites avec vue lagon", "disponible", "Vue Exceptionnelle", 1, 1, 4.96, 26, "[\"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80\",\"https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80\"]", "[\"Piscine miroir face au soleil couchant\",\"Grand ponton aménagé avec salon lounge\",\"4 suites climatisées avec dressing et vue lagune\",\"Table de billard & jeux\",\"Wi-Fi Starlink haut débit\",\"Cuisine américaine haut de gamme\",\"Espace barbecue & plancha\",\"Système de secours électrique automatique\",\"Gouvernante et veilleur de nuit\",\"Accès facile aux pinasses et bateaux pour La Passe\"]", "[\"Coucher de soleil féerique\",\"Table de billard\",\"Ponton lounge\",\"Finition grand luxe\"]", 5)
  ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `tagline`=VALUES(`tagline`), `category`=VALUES(`category`), `category_label`=VALUES(`category_label`), `location`=VALUES(`location`), `description`=VALUES(`description`), `price_per_night`=VALUES(`price_per_night`), `price_euro`=VALUES(`price_euro`), `weekend_package`=VALUES(`weekend_package`), `capacity`=VALUES(`capacity`), `bedrooms`=VALUES(`bedrooms`), `bathrooms`=VALUES(`bathrooms`), `beds`=VALUES(`beds`), `status`=VALUES(`status`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `rating`=VALUES(`rating`), `reviews_count`=VALUES(`reviews_count`), `images`=VALUES(`images`), `features`=VALUES(`features`), `highlights`=VALUES(`highlights`), `sort_order`=VALUES(`sort_order`);

-- 4 ligne(s) dans `terrains`
INSERT INTO `terrains` (`id`, `reference`, `title`, `location`, `district`, `area_sqm`, `price_total`, `price_per_sqm`, `price_euro`, `land_status`, `land_status_label`, `utilities`, `status`, `description`, `images`, `highlights`, `visible`, `featured`, `badge`, `latitude`, `longitude`, `sort_order`)
  VALUES ("terrain-lagune-km12", "TER-ASS-001", "Parcelle pied dans l’eau — Lagune Aby", "Assinie-Mafia, Km 12 (bord de lagune)", "Lotissement Aby Résidence", 1200, 96000000, 80000, 146351, "titre-foncier", "Titre foncier", "[\"eau\",\"electricite\",\"voie-bitumee\",\"borne\"]", "disponible", "Parcelle rectangulaire de 1 200 m² avec 24 mètres de façade directe sur la lagune Aby. Terrain plat, remblayé et borné, adapté à la construction d’une villa avec ponton privé. Raccordements eau et électricité en limite de parcelle. Accès par voie bitumée depuis la route d’Assinie.", "[\"assets/images/residence-villa-luxe.jpg\"]", "[\"24 m de façade lagune\",\"Terrain borné et remblayé\",\"Ponton privatif réalisable\",\"Voie bitumée jusqu’à la parcelle\"]", 1, 1, "Exclusivité", 5.1421, -3.2894, 0)
  ON DUPLICATE KEY UPDATE `reference`=VALUES(`reference`), `title`=VALUES(`title`), `location`=VALUES(`location`), `district`=VALUES(`district`), `area_sqm`=VALUES(`area_sqm`), `price_total`=VALUES(`price_total`), `price_per_sqm`=VALUES(`price_per_sqm`), `price_euro`=VALUES(`price_euro`), `land_status`=VALUES(`land_status`), `land_status_label`=VALUES(`land_status_label`), `utilities`=VALUES(`utilities`), `status`=VALUES(`status`), `description`=VALUES(`description`), `images`=VALUES(`images`), `highlights`=VALUES(`highlights`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `badge`=VALUES(`badge`), `latitude`=VALUES(`latitude`), `longitude`=VALUES(`longitude`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `terrains` (`id`, `reference`, `title`, `location`, `district`, `area_sqm`, `price_total`, `price_per_sqm`, `price_euro`, `land_status`, `land_status_label`, `utilities`, `status`, `description`, `images`, `highlights`, `visible`, `featured`, `badge`, `latitude`, `longitude`, `sort_order`)
  VALUES ("terrain-ocean-mafia", "TER-ASS-002", "Terrain balnéaire second rideau — Océan", "Assinie-Mafia, côté océan", "Quartier Mafia Plage", 800, 48000000, 60000, 73176, "acd", "ACD (Arrêté de Concession Définitive)", "[\"eau\",\"electricite\",\"cloture\"]", "disponible", "Parcelle de 800 m² située en second rideau de la plage, à 120 mètres de l’océan. Déjà clôturée sur trois côtés. Environnement résidentiel calme, idéal pour une résidence secondaire ou un projet locatif saisonnier.", "[\"assets/images/residence-ocean-assinie.jpg\"]", "[\"À 120 m de l’océan\",\"Déjà clôturé\",\"ACD en cours de mutation\",\"Zone résidentielle calme\"]", 1, 1, "", 5.1305, -3.2762, 1)
  ON DUPLICATE KEY UPDATE `reference`=VALUES(`reference`), `title`=VALUES(`title`), `location`=VALUES(`location`), `district`=VALUES(`district`), `area_sqm`=VALUES(`area_sqm`), `price_total`=VALUES(`price_total`), `price_per_sqm`=VALUES(`price_per_sqm`), `price_euro`=VALUES(`price_euro`), `land_status`=VALUES(`land_status`), `land_status_label`=VALUES(`land_status_label`), `utilities`=VALUES(`utilities`), `status`=VALUES(`status`), `description`=VALUES(`description`), `images`=VALUES(`images`), `highlights`=VALUES(`highlights`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `badge`=VALUES(`badge`), `latitude`=VALUES(`latitude`), `longitude`=VALUES(`longitude`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `terrains` (`id`, `reference`, `title`, `location`, `district`, `area_sqm`, `price_total`, `price_per_sqm`, `price_euro`, `land_status`, `land_status_label`, `utilities`, `status`, `description`, `images`, `highlights`, `visible`, `featured`, `badge`, `latitude`, `longitude`, `sort_order`)
  VALUES ("terrain-lotissement-passe", "TER-ASS-003", "Lot viabilisé — Résidence de La Passe", "Assinie, secteur La Passe", "Lotissement La Passe", 500, 22500000, 45000, 34301, "lettre-attribution", "Lettre d’attribution", "[\"eau\",\"electricite\",\"voie-bitumee\",\"assainissement\",\"borne\"]", "reserve", "Lot de 500 m² dans un lotissement entièrement viabilisé : voirie, réseau d’eau, électricité et assainissement en place. Bornage réalisé, plan de lotissement approuvé. Proche des commerces et du débarcadère.", "[\"assets/images/plage-assinie-passe.jpg\"]", "[\"Lotissement viabilisé\",\"Bornage réalisé\",\"Proche débarcadère\",\"Assainissement en place\"]", 1, 0, "Réservé", 5.1198, -3.2641, 2)
  ON DUPLICATE KEY UPDATE `reference`=VALUES(`reference`), `title`=VALUES(`title`), `location`=VALUES(`location`), `district`=VALUES(`district`), `area_sqm`=VALUES(`area_sqm`), `price_total`=VALUES(`price_total`), `price_per_sqm`=VALUES(`price_per_sqm`), `price_euro`=VALUES(`price_euro`), `land_status`=VALUES(`land_status`), `land_status_label`=VALUES(`land_status_label`), `utilities`=VALUES(`utilities`), `status`=VALUES(`status`), `description`=VALUES(`description`), `images`=VALUES(`images`), `highlights`=VALUES(`highlights`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `badge`=VALUES(`badge`), `latitude`=VALUES(`latitude`), `longitude`=VALUES(`longitude`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `terrains` (`id`, `reference`, `title`, `location`, `district`, `area_sqm`, `price_total`, `price_per_sqm`, `price_euro`, `land_status`, `land_status_label`, `utilities`, `status`, `description`, `images`, `highlights`, `visible`, `featured`, `badge`, `latitude`, `longitude`, `sort_order`)
  VALUES ("terrain-grand-lot-agrement", "TER-ASS-004", "Grand lot d’agrément — 3 000 m²", "Assinie-Mafia, Km 16", "Zone Km 16", 3000, 150000000, 50000, 228674, "titre-foncier", "Titre foncier", "[\"electricite\",\"voie-bitumee\",\"borne\"]", "disponible", "Grande parcelle de 3 000 m² plantée de cocotiers, adaptée à un projet hôtelier, un éco-lodge ou une résidence familiale de grande capacité. Titre foncier disponible, terrain libre de toute occupation.", "[\"assets/images/quad-plage-assinie.jpg\"]", "[\"3 000 m² d’un seul tenant\",\"Planté de cocotiers\",\"Titre foncier disponible\",\"Libre de toute occupation\"]", 1, 0, "Projet hôtelier", 5.1487, -3.3012, 3)
  ON DUPLICATE KEY UPDATE `reference`=VALUES(`reference`), `title`=VALUES(`title`), `location`=VALUES(`location`), `district`=VALUES(`district`), `area_sqm`=VALUES(`area_sqm`), `price_total`=VALUES(`price_total`), `price_per_sqm`=VALUES(`price_per_sqm`), `price_euro`=VALUES(`price_euro`), `land_status`=VALUES(`land_status`), `land_status_label`=VALUES(`land_status_label`), `utilities`=VALUES(`utilities`), `status`=VALUES(`status`), `description`=VALUES(`description`), `images`=VALUES(`images`), `highlights`=VALUES(`highlights`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `badge`=VALUES(`badge`), `latitude`=VALUES(`latitude`), `longitude`=VALUES(`longitude`), `sort_order`=VALUES(`sort_order`);

-- 6 ligne(s) dans `activities`
INSERT INTO `activities` (`id`, `title`, `subtitle`, `description`, `image`, `images`, `duration`, `price`, `badge`, `visible`, `featured`, `sort_order`)
  VALUES ("balade-bateau", "Balade privée en Bateau vers La Passe", "L'incontournable d'Assinie", "Embarquez depuis le ponton de votre villa pour une navigation le long de la lagune jusqu'à la mythique Passe d'Assinie, où les eaux calmes de la lagune Aby rencontrent la houle de l'océan Atlantique. Arrêt sur les bancs de sable préservés.", "assets/images/bateau-excursion-lagune.jpg", "[\"assets/images/bateau-excursion-lagune.jpg\"]", "2 heures ou demi-journée", "À partir de 60 000 FCFA / sortie", "Top Activité", 1, 0, 0)
  ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `subtitle`=VALUES(`subtitle`), `description`=VALUES(`description`), `image`=VALUES(`image`), `images`=VALUES(`images`), `duration`=VALUES(`duration`), `price`=VALUES(`price`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `activities` (`id`, `title`, `subtitle`, `description`, `image`, `images`, `duration`, `price`, `badge`, `visible`, `featured`, `sort_order`)
  VALUES ("jet-ski", "Sensations Jet Ski & Bouée Tractée", "Adrénaline sur la lagune", "Pilotez des Jet Skis dernière génération sur les vastes étendues calmes de la lagune d'Assinie en toute sécurité. Possibilité de bouée tractée pour les amateurs de fous rires en famille ou entre amis.", "assets/images/jetski-lagune-assinie.jpg", "[\"assets/images/jetski-lagune-assinie.jpg\"]", "30 min ou 1 heure", "45 000 FCFA / 30 min", "Sensations Fortes", 1, 0, 1)
  ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `subtitle`=VALUES(`subtitle`), `description`=VALUES(`description`), `image`=VALUES(`image`), `images`=VALUES(`images`), `duration`=VALUES(`duration`), `price`=VALUES(`price`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `activities` (`id`, `title`, `subtitle`, `description`, `image`, `images`, `duration`, `price`, `badge`, `visible`, `featured`, `sort_order`)
  VALUES ("iles-ehotiles", "Excursion aux Îles Éhotilés", "Parc National & Nature Sauvage", "Découverte guidée de l'archipel historique des Îles Éhotilés, réserve naturelle protégée abritant une faune exceptionnelle, des lamantins, des oiseaux migrateurs et des arbres centenaires sacrés.", "assets/images/plage-assinie-passe.jpg", "[\"assets/images/plage-assinie-passe.jpg\"]", "Demi-journée avec guide", "75 000 FCFA pour le groupe", "Écotourisme", 1, 0, 2)
  ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `subtitle`=VALUES(`subtitle`), `description`=VALUES(`description`), `image`=VALUES(`image`), `images`=VALUES(`images`), `duration`=VALUES(`duration`), `price`=VALUES(`price`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `activities` (`id`, `title`, `subtitle`, `description`, `image`, `images`, `duration`, `price`, `badge`, `visible`, `featured`, `sort_order`)
  VALUES ("randonnee-quad", "Randonnée Quad sur les Pistes & Plages", "Aventure tout-terrain", "Partez en raid guidé à travers les pistes sablonneuses bordées de cocotiers et les plages désertes d'Assinie-Mafia. Une expérience exaltante pour découvrir la région sous un autre angle.", "assets/images/quad-plage-assinie.jpg", "[\"assets/images/quad-plage-assinie.jpg\"]", "1h30 de circuit", "35 000 FCFA / quad", "Aventure", 1, 0, 3)
  ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `subtitle`=VALUES(`subtitle`), `description`=VALUES(`description`), `image`=VALUES(`image`), `images`=VALUES(`images`), `duration`=VALUES(`duration`), `price`=VALUES(`price`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `activities` (`id`, `title`, `subtitle`, `description`, `image`, `images`, `duration`, `price`, `badge`, `visible`, `featured`, `sort_order`)
  VALUES ("parc-dipi", "Visite du Parc Zoologique Dipi", "Rencontre avec la faune locale", "Idéal pour les enfants et les passionnés de nature : visitez le sanctuaire Dipi à Assinie, célèbre pour ses crocodiles géants, singes, serpents et tortues géantes dans un cadre verdoyant ombragé.", "assets/images/crocodiles-parc-dipi.jpg", "[\"assets/images/crocodiles-parc-dipi.jpg\"]", "1h30 de visite", "Entrée 5 000 FCFA / personne", "En Famille", 1, 0, 4)
  ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `subtitle`=VALUES(`subtitle`), `description`=VALUES(`description`), `image`=VALUES(`image`), `images`=VALUES(`images`), `duration`=VALUES(`duration`), `price`=VALUES(`price`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `activities` (`id`, `title`, `subtitle`, `description`, `image`, `images`, `duration`, `price`, `badge`, `visible`, `featured`, `sort_order`)
  VALUES ("chef-prive", "Chef Cuisinier Privé & Restauration Lagune", "Gastronomie & Saveurs locales", "Dégustez à la villa des carpes et mérous braisés au feu de bois, langoustes fraîches d'Assinie grillées au beurre persillé, attiéké huile rouge, alloco doré ou menus européens préparés par notre chef dédié.", "assets/images/activite-chef-prive-v2.png", "[\"assets/images/activite-chef-prive-v2.png\"]", "Par journée ou week-end", "À partir de 25 000 FCFA / jour", "Gourmand", 1, 0, 5)
  ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `subtitle`=VALUES(`subtitle`), `description`=VALUES(`description`), `image`=VALUES(`image`), `images`=VALUES(`images`), `duration`=VALUES(`duration`), `price`=VALUES(`price`), `badge`=VALUES(`badge`), `visible`=VALUES(`visible`), `featured`=VALUES(`featured`), `sort_order`=VALUES(`sort_order`);

-- 3 ligne(s) dans `reviews`
INSERT INTO `reviews` (`id`, `author`, `city`, `stay`, `rating`, `date_label`, `comment`, `avatar`, `visible`, `sort_order`)
  VALUES ("avis-1", "Marc & Diane K.", "Abidjan, Cocody", "Séjour en famille à la Villa L'Oasis", 5, "Il y a 2 semaines", "Nous avons passé un week-end tout simplement magique ! La villa est encore plus belle en vrai que sur les photos de la page Facebook. Le ponton privé nous a permis d'embarquer directement en bateau pour La Passe. Le personnel était aux petits soins et la piscine était d'une propreté irréprochable. Nous reviendrons sans hésiter !", "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80", 1, 0)
  ON DUPLICATE KEY UPDATE `author`=VALUES(`author`), `city`=VALUES(`city`), `stay`=VALUES(`stay`), `rating`=VALUES(`rating`), `date_label`=VALUES(`date_label`), `comment`=VALUES(`comment`), `avatar`=VALUES(`avatar`), `visible`=VALUES(`visible`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `reviews` (`id`, `author`, `city`, `stay`, `rating`, `date_label`, `comment`, `avatar`, `visible`, `sort_order`)
  VALUES ("avis-2", "Christelle B.", "Abidjan, Plateau", "Anniversaire au Domaine Éden", 5, "Il y a 1 mois", "J'ai fêté mes 30 ans avec 35 amis au Domaine Éden. Organisation parfaite via WhatsApp avec l'équipe de Détente et Loisirs. Le bar aquatique dans la piscine a fait l'unanimité. Merci pour le professionnalisme et la réactivité du service client !", "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80", 1, 1)
  ON DUPLICATE KEY UPDATE `author`=VALUES(`author`), `city`=VALUES(`city`), `stay`=VALUES(`stay`), `rating`=VALUES(`rating`), `date_label`=VALUES(`date_label`), `comment`=VALUES(`comment`), `avatar`=VALUES(`avatar`), `visible`=VALUES(`visible`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `reviews` (`id`, `author`, `city`, `stay`, `rating`, `date_label`, `comment`, `avatar`, `visible`, `sort_order`)
  VALUES ("avis-3", "Patrick & Sandra V.", "Expatriés français résidents en Côte d'Ivoire", "Séjour à la Résidence Palm Beach", 5, "Il y a 3 semaines", "Le luxe d'être les pieds dans l'eau côté océan sans aucun vis-à-vis. Les enfants ont adoré la plage et la piscine privée, et le groupe électrogène a assuré une électricité sans coupure tout le week-end avec la clim au frais. Recommandé à 100%.", "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80", 1, 2)
  ON DUPLICATE KEY UPDATE `author`=VALUES(`author`), `city`=VALUES(`city`), `stay`=VALUES(`stay`), `rating`=VALUES(`rating`), `date_label`=VALUES(`date_label`), `comment`=VALUES(`comment`), `avatar`=VALUES(`avatar`), `visible`=VALUES(`visible`), `sort_order`=VALUES(`sort_order`);

-- 6 ligne(s) dans `faq`
INSERT INTO `faq` (`id`, `question`, `answer`, `visible`, `sort_order`)
  VALUES ("faq-1", "", "", 1, 0)
  ON DUPLICATE KEY UPDATE `question`=VALUES(`question`), `answer`=VALUES(`answer`), `visible`=VALUES(`visible`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `faq` (`id`, `question`, `answer`, `visible`, `sort_order`)
  VALUES ("faq-2", "", "", 1, 1)
  ON DUPLICATE KEY UPDATE `question`=VALUES(`question`), `answer`=VALUES(`answer`), `visible`=VALUES(`visible`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `faq` (`id`, `question`, `answer`, `visible`, `sort_order`)
  VALUES ("faq-3", "", "", 1, 2)
  ON DUPLICATE KEY UPDATE `question`=VALUES(`question`), `answer`=VALUES(`answer`), `visible`=VALUES(`visible`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `faq` (`id`, `question`, `answer`, `visible`, `sort_order`)
  VALUES ("faq-4", "", "", 1, 3)
  ON DUPLICATE KEY UPDATE `question`=VALUES(`question`), `answer`=VALUES(`answer`), `visible`=VALUES(`visible`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `faq` (`id`, `question`, `answer`, `visible`, `sort_order`)
  VALUES ("faq-5", "", "", 1, 4)
  ON DUPLICATE KEY UPDATE `question`=VALUES(`question`), `answer`=VALUES(`answer`), `visible`=VALUES(`visible`), `sort_order`=VALUES(`sort_order`);
INSERT INTO `faq` (`id`, `question`, `answer`, `visible`, `sort_order`)
  VALUES ("faq-6", "", "", 1, 5)
  ON DUPLICATE KEY UPDATE `question`=VALUES(`question`), `answer`=VALUES(`answer`), `visible`=VALUES(`visible`), `sort_order`=VALUES(`sort_order`);

-- 6 ligne(s) dans `settings`
INSERT INTO `settings` (`setting_key`, `value`)
  VALUES ("heroTitle", "\"Là où vos rêves prennent vie\"")
  ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `settings` (`setting_key`, `value`)
  VALUES ("heroSubtitle", "\"Des villas d’exception entre lagune et océan, pensées pour vos plus beaux souvenirs.\"")
  ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `settings` (`setting_key`, `value`)
  VALUES ("phone", "\"+225 07 67 69 63 18\"")
  ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `settings` (`setting_key`, `value`)
  VALUES ("facebookPage", "\"https://web.facebook.com/profile.php?id=100075922063365\"")
  ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `settings` (`setting_key`, `value`)
  VALUES ("officeHours", "\"7j/7 · 7h–22h\"")
  ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `settings` (`setting_key`, `value`)
  VALUES ("currency", "\"FCFA\"")
  ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

-- Contrôle final : décompte par table
SELECT 'villas' AS type, COUNT(*) AS total FROM `villas`
UNION ALL SELECT 'terrains', COUNT(*) FROM `terrains`
UNION ALL SELECT 'activites', COUNT(*) FROM `activities`
UNION ALL SELECT 'avis', COUNT(*) FROM `reviews`
UNION ALL SELECT 'faq', COUNT(*) FROM `faq`
UNION ALL SELECT 'reglages', COUNT(*) FROM `settings`;
